### PR TITLE
FIX: success message being displayed on empty notes

### LINKED ISSUE #12: [BUG]: Toast message being displayed on empty note
When attempting to add an empty note, the toast message is being displayed, providing a misleading indication of a successful note addition. This behavior is not consistent with the intended functionality, as the toast message should only appear on successful note additions

### Screenshot:

image

### Proposed Solution:

Implement a validation check to prevent the display of the toast message when attempting to add an empty note.

### PR DESCRIPTION
**Pull request by bj-jiwrajka**
This pull request addresses an issue where the success message was incorrectly displayed even when attempting to add an empty note. The fix ensures that the success message is only shown on successful note additions

Closes #12

### CODE REVIEW

**Comment by bj-jiwrajka** [comment]
Please review and merge @Nitya-Pasrija

**Comment by nisha-laur** [comment]
@bj-jiwrajka It appears that there is a merge conflict in the "app.js" file. The conflict arises from changes made in the current branch and the "main" branch. You can try this 
`//DOM selectors
showNotes();
let addbtn = document.getElementById("addBtn");
let done = document.getElementById("editBtn");
let addtext = document.getElementById("addTxt");
let searchTxt = document.getElementById("searchTxt");
let heading = document.getElementById("heading");
let volumeButton = document.getElementById('mute-button');
let styledMessageContainer = document.getElementById("styled-message-container");
done.style.visibility = "hidden";  // Assuming you want to keep this line

//Event listeners
addbtn.addEventListener("click", addaNote);
searchTxt.addEventListener("input", searchtext);

//Functions
// ... (rest of the functions remain unchanged)
`

In this resolution, both the changes related to the volumeButton and styledMessageContainer are included. If there are further conflicts or specific lines you want to keep or discard, adjust the code accordingly.

**Comment by bj-jiwrajka** [comment]
> @bj-jiwrajka It appears that there is a merge conflict in the "app.js" file. The conflict arises from changes made in the current branch and the "main" branch. You can try this `//DOM selectors showNotes(); let addbtn = document.getElementById("addBtn"); let done = document.getElementById("editBtn"); let addtext = document.getElementById("addTxt"); let searchTxt = document.getElementById("searchTxt"); let heading = document.getElementById("heading"); let volumeButton = document.getElementById('mute-button'); let styledMessageContainer = document.getElementById("styled-message-container"); done.style.visibility = "hidden"; // Assuming you want to keep this line
> 
> //Event listeners addbtn.addEventListener("click", addaNote); searchTxt.addEventListener("input", searchtext);
> 
> //Functions // ... (rest of the functions remain unchanged) `
> 
> In this resolution, both the changes related to the volumeButton and styledMessageContainer are included. If there are further conflicts or specific lines you want to keep or discard, adjust the code accordingly.

I've fixed the merge conflicts, can you please check it now.

**Comment by nisha-laur** [comment]
Good Work @bj-jiwrajka

**Comment by bj-jiwrajka** [comment]
> Good Work @bj-jiwrajka

Thank you @nisha-laur ma'am🙇🚀

**Pull request merged**
