### PR TITLE
FIX: Color of toast message in light mode

### LINKED ISSUE #14: [BUG] : Toast Message Color Invisibility in White Mode
The toast message color is not clearly visible when the application is in white mode. This affects the overall user experience, making it difficult for users to read or notice the toast messages.

The toast message color should be visible and clearly distinguishable when the application is in white mode.

Screenshot:

image

### PR DESCRIPTION
**Pull request by bj-jiwrajka**
1.  Formatted the CSS 
2.  Removed unused images
3.  Fixed the color of toast message in light mode which was not visible earlier due to white bg. Closes #14

### CODE REVIEW

**Comment by bj-jiwrajka** [comment]
@nisha-laur  please review my PR

**Comment by bj-jiwrajka** [comment]
@nisha-laur fixed the merge conflict; please review now:)

**Review by Nitya-Pasrija — APPROVED** [review]
Looks good :)

**Comment by nisha-laur** [comment]
@bj-jiwrajka  Can you share some screenshots because at my end the issue still persists 
image

**Comment by bj-jiwrajka** [comment]
I've fixed the issue now, you can check @nisha-laur , here are the screenshots:

image
image

**Pull request merged**
