### PR TITLE
[Fix]:Fixes height and width of notes card

### PR DESCRIPTION
**Pull request by ShaikArshidBanu**
fixes issue #21  by additionally implementing changes mentioned in #22 

solution obtained:
Screenshot 2024-01-02 141057

### CODE REVIEW

**Comment by iaayushmaan** [comment]
@ShaikArshidBanu I don't think this aligns with the description that @nisha-laur gave. You have to use a grid layout, rather than mere flex-box.

**Comment by nisha-laur** [comment]
yeah @ShaikArshidBanu  your code is just expanding the width of the notes div which is not looking nice . You are supposed to make a grid layout in which the height of the div changes in accordance with the width in relation the length of the text in it . Please look into that .

**Comment by ShaikArshidBanu** [comment]
> yeah @ShaikArshidBanu your code is just expanding the width of the notes div which is not looking nice . You are supposed to make a grid layout in which the height of the div changes in accordance with the width in relation the length of the text in it . Please look into that .

Okay I'll look into it

**Comment by ShaikArshidBanu** [comment]
@nisha-laur in order to achieve the layout as described in #22 we have to fix the height of index.html page not all the notes can be saved in that format in case of large number of notes and as an alternative solution we should provide an additional button to view all the saved notes so that we can navigate to new page which contains list of all the notes and we can view each notes by clicking that notesconatiner in which we can further add fetures like sorting according to time or alphabetical order of title.
 I would like to work on this if you assign it to me.

**Comment by nisha-laur** [comment]
@ShaikArshidBanu Okay you can try that .

**Comment by ShaikArshidBanu** [comment]
> @ShaikArshidBanu Okay you can try that .

@nisha-laur Okay I'll work on this

**Pull request closed without merging**
