### PR TITLE
ADD: Toast message instead of alert for empty title

### LINKED ISSUE #39: [FEAT]: Toast message for empty title instead of alert
When we do not enter a title, it shows an alert like this: 

image

However, UI can be improved by showing a toast message exactly similar to the case when notes section is empty like this:

image

### PR DESCRIPTION
**Pull request by bj-jiwrajka**
This PR closes #39  and displays a beautiful toast message instead of an alert when the title section is empty

Light Mode:

image

Dark Mode:

image

### CODE REVIEW

**Comment by bj-jiwrajka** [comment]
@nisha-laur please review this:)

**Comment by nisha-laur** [comment]
@bj-jiwrajka resolve the conflicts

**Comment by bj-jiwrajka** [comment]
> @bj-jiwrajka resolve the conflicts

done :)

**Comment by nisha-laur** [comment]
image

**Comment by bj-jiwrajka** [comment]
> image

fixed it now:)

**Pull request merged**
