### PR TITLE
Background image addition

### PR DESCRIPTION
**Pull request by AakxSha**
issue #2 
Screenshot 2023-12-29 205819
Screenshot 2023-12-29 205807

### CODE REVIEW

**Comment by nisha-laur** [comment]
@AakxSha Resolve the conflicts .

**Comment by AakxSha** [comment]
@nisha-laur i have resolved the conflicts. please check now.

**Comment by nisha-laur** [comment]
@AakxSha The heading is getting displayed two times 
image
and also I don't like the UI much , because it is not looking clean and making it look crowdy  . Can you please come up with a better UI .

**Comment by AakxSha** [comment]
Sure

**Pull request closed without merging**
