### PR TITLE
fix: Height and width of the notes container

### LINKED ISSUE #21: [BUG]: Notes container is not fit to the content.
The height and Width of notes container are not fit to the content.

Current issue:
Screenshot 2023-12-30 142605

Propsed Solution:
Screenshot 2023-12-30 144246

### PR DESCRIPTION
**Pull request by iaayushmaan**
The height and width of the container are now fixed to content.

Fixes #21 

Screenshot 2023-12-31 014317

- Bug fix (non-breaking change which fixes an issue)

- [X] Self-reviewed the code.

### CODE REVIEW

**Comment by ShaikArshidBanu** [comment]
This issue was assigned to me.

**Comment by iaayushmaan** [comment]
When I solved this issue, there hadn't been any assignments made to it at that time.

**Comment by ShaikArshidBanu** [comment]
> When I solved this issue, there hadn't been any assignments made to it at that time.

@iaayushmaan According to the code of conduct you should get the issue assigned to you before you solve it.only those who get assigned the issue can solve it.

**Comment by nisha-laur** [comment]
@iaayushmaan @ShaikArshidBanu  . See It's okay but from next time please do take care of it . For now , I will reveiw @iaayushmaan PR and if it is fine then @iaayushmaan Please first get the issue assigned first before raising a PR and If there is some modifications to be done . Then @ShaikArshidBanu  you can start working on this issue .

**Comment by nisha-laur** [comment]
@iaayushmaan The issue still exist and also  not that while raising a PR you attach the screen shots of before and after .

**Comment by iaayushmaan** [comment]
@nisha-laur In my browser, It worked absolutely fine. Pl check the file changes and recommend what went wrong.
Regards

**Comment by nisha-laur** [comment]
@iaayushmaan Add screen shots of Before and After

**Comment by nisha-laur** [comment]
This is What I can see
image
and you have just added 'align-items-start ' class in the div . But does not seem to resolve the issue .Let me clearify the issue . This issue is supposed to correct the width and height of the notes div like a grid :-
image
I hope , you got now . If not feel free to ask .

**Comment by iaayushmaan** [comment]
@nisha-laur I misunderstood the issue, but Now, I got it. Thanks!
@ShaikArshidBanu Address the issue with full description like @nisha-laur did. Hope you find the difference.
Regards

**Pull request closed without merging**
