### PR TITLE
Reaolving faq section

### PR DESCRIPTION
**Pull request by Garima-149**
# issue  no.24 @Nitya-Pasrija @nisha-laur 
Screenshot (14)

### CODE REVIEW

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
Can you realign the length of the Faq section's CSS so that it looks neat, also would recommend having a dark blue background with white text for the FAQ section

**Comment by Garima-149** [comment]
Screenshot (16)
@Nitya-Pasrija @nisha-laur Is it fine ? @ayushichoudhary-19 
Screenshot (16)
Or should I  make more changes?

**Comment by Garima-149** [comment]
@Nitya-Pasrija @ayushichoudhary-19 @nisha-laur please tell should I make further changes or is it fine? 
or please merge my pr?

**Comment by nisha-laur** [comment]
The UI of this page is not looking good ;(

**Comment by Garima-149** [comment]
@nisha-laur Should I change it to previous styling as you accepted it and allowed me to make pr?

**Comment by Nitya-Pasrija** [comment]
@Garima-149 do a git pull instead so that the conflicts get resolved

**Comment by Garima-149** [comment]
@Nitya-Pasrija I resolved conflicts

**Review by Nitya-Pasrija — APPROVED** [review]

**Pull request merged**
