### PR TITLE
ADD: Edit time

### PR DESCRIPTION
**Pull request by bj-jiwrajka**
This PR now marks a note as Edited (with its edit time). It solves the issue #10 and has the following features:

1. Display Location: The "last edited" timestamp should be visible within the note interface, near the top or bottom of the note content.
2. Automatic Update: Whenever a user edits a note, the "last edited" timestamp should be automatically updated to reflect the current date and time.
3. Visibility Control: Users should have the option to toggle the visibility of the "last edited" timestamp. This feature is to accommodate users who prefer a cleaner interface without this information.

### CODE REVIEW

**Comment by bj-jiwrajka** [comment]
@nisha-laur please review my PR; loved to work on this feature :-)

**Comment by nisha-laur** [comment]
Before adding the Edit time . Is the edit option / button is functional . Because I don't thing we are able edit the notes . If you are , Can you share a short video of that ?

**Comment by bj-jiwrajka** [comment]
> Before adding the Edit time . Is the edit option / button is functional . Because I don't thing we are able edit the notes . If you are , Can you share a short video of that ?

yes, the edit button is functional and working absolutely fine, I'm attaching the video in next comment :👇

**Comment by bj-jiwrajka** [comment]
Here are the screenshots:

image
image

and yeah I've fixed the merge conflicts too, you can now merge it without worries 👌

**Comment by nisha-laur** [comment]
Keep Up the good work !🎉

**Comment by bj-jiwrajka** [comment]
closes #10

**Pull request merged**
