### PR TITLE
This PR addresses Issue#29, Issue#30 and Issue#35. As all of these are progressive code changes.

### PR DESCRIPTION
**Pull request by rajneesh069**
This will give cleaner code structure as all the styling code will be at one place.

### CODE REVIEW

**Comment by nisha-laur** [comment]
@rajneesh069 resolve the conflicts .

**Comment by rajneesh069** [comment]
> @rajneesh069 resolve the conflicts .

image
The option is greyed out and I tried pulling the changes on VSCode, but it says it's up to date with the origin/Issue#30 branch.

**Comment by nisha-laur** [comment]
It should be up to date with the origin/main branch.

**Comment by rajneesh069** [comment]
> It should be up to date with the origin/main branch.

I've made a new PR with a branch name RedoChanges, that'll fix all those errors. You can safely merge it and it will address all the changes made in this PR. I hope its helpful. And you could close this one if you'd like, its pretty much redundant because of that branch.

**Pull request closed without merging**
